select count (PRIMARY_TYPE)
from CRIME;

select *
from CRIME
limit 10;


select count(ARREST)
from CRIME
where ARREST = "TRUE";

select avg (SAFETY_SCORE)
from SCHOOLS;

select (COMMUNITY_AREA_NAME)
from CENSUS_DATA
where COMMUNITY_AREA_NAME like 'B%';

 select distinct (PRIMARY_TYPE)
 from CRIME
 where LOCATION_DESCRIPTION = 'GAS STATION';
 
 select (NAME_OF_SCHOOL)
 from SCHOOLS
 where COMMUNITY_AREA_NUMBER between 10 and 15 and HEALTHY_SCHOOL_CERTIFIED = 'Yes';
 
 select (COMMUNITY_AREA_NAME), avg (COLLEGE_ENROLLMENT) as Avg_Enrollment
 from SCHOOLS group by COMMUNITY_AREA_NAME
 order by (Avg_Enrollment) desc
 limit 5;
 
 select COMMUNITY_AREA_NAME, SAFETY_SCORE
 from SCHOOLS
 where SAFETY_SCORE in (select SAFETY_SCORE
 from SCHOOLS
 order by SAFETY_SCORE asc
 limit 1);
 
 select SCHOOLS.COMMUNITY_AREA_NAME, SCHOOLS.COMMUNITY_AREA_NUMBER, PER_CAPITA_INCOME
 from SCHOOLS, CENSUS_DATA
 where SAFETY_SCORE = 1 and  SCHOOLS.COMMUNITY_AREA_NUMBER =  CENSUS_DATA.COMMUNITY_AREA_NUMBER ;
 
select "School_ID", NAME_OF_SCHOOL, "City"
from SCHOOLS
where SAFETY_SCORE < (select avg (SAFETY_SCORE)
from SCHOOLS);
 
 select CENSUS_DATA.COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
 from SCHOOLS INNER JOIN CENSUS_DATA
 on SAFETY_SCORE = 1 and  SCHOOLS.COMMUNITY_AREA_NUMBER =  CENSUS_DATA.COMMUNITY_AREA_NUMBER;
 